#!/bin/bash

################################################################################################
### cifar configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job. main: all nodes; gtx1080: 1080 gpu card nodes; rtx2080: 2080 nodes; teslap100: p100 nodes; titanrtx: titan nodes
##SBATCH --qos azencot
#SBATCH --gpus=rtx_6000:1			# 1 GPU
#SBATCH --time 7-00:00:00			### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --job-name train			### name of the job
#SBATCH --output train-%J.out			### output log for running job - %J for job number
##SBATCH --exclude=cs-6000-04,ise-cpu256-06,cs-cpu256-01,ise-cpu256-16,ise-cpu256-15,ise-cpu256-22,ise-cpu256-14,ise-cpu256-13,ise-cpu256-12,ise-cpu256-11,ise-cpu256-10,ise-cpu256-09,ise-cpu256-08,ise-cpu256-07,ise-cpu256-05,ise-cpu256-04,ise-cpu256-03,ise-cpu256-02,ise-cpu256-01,ise-cpu256-21,ise-cpu256-18,ise-cpu256-20,ise-cpu256-19,ise-cpu256-17,ise-cpu256-23,ise-cpu256-24,ise-cpu256-25,ise-cpu256-26,ise-cpu256-27,ise-cpu256-28,ise-cpu256-29,ise-cpu256-30,ise-cpu256-31,ise-cpu256-32

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
module load anaconda				### load anaconda module (must be present when working with conda environments)
#source activate /home/bermann/.conda/envs/edm/				### activate a conda environment, replace my_env with your conda environment
source activate /home/naimani/.conda/envs/edm				### activate a conda environment, replace my_env with your conda environment

export PYTHONPATH=/cs_storage/bermann/functional_mapping:$PYTHONPATH

# latent space scaling
python train.py --config_name koopman/cifar_uncond --neptune True
#python train.py --config_name koopman/cifar_uncond_fast --neptune True
#python train.py --config_name koopman/cifar_cond --neptune True